In [15]:
import cv2
import random

In [2]:
img=cv2.imread('animegirl.jpg')

In [4]:
print(img) # we get the numpy array

[[[17  8  5]
  [17  8  5]
  [17  8  5]
  ...
  [76 33 54]
  [76 33 54]
  [76 33 54]]

 [[17  8  5]
  [17  8  5]
  [17  8  5]
  ...
  [76 33 54]
  [76 33 54]
  [76 33 54]]

 [[17  8  5]
  [17  8  5]
  [17  8  5]
  ...
  [76 33 54]
  [76 33 54]
  [76 33 54]]

 ...

 [[16  5  7]
  [16  5  7]
  [17  6  8]
  ...
  [44 11 15]
  [44 11 15]
  [44 11 15]]

 [[16  5  7]
  [16  5  7]
  [17  6  8]
  ...
  [44 11 15]
  [44 11 15]
  [44 11 15]]

 [[16  5  7]
  [16  5  7]
  [17  6  8]
  ...
  [44 11 15]
  [44 11 15]
  [44 11 15]]]


In [5]:
print(type(img))

<class 'numpy.ndarray'>


In [8]:
print(img.shape) # ht wd channel(color space)

(1080, 1920, 3)


In [10]:
# [
#     [[],[],[],[].......]
#     [[],[],[],[].......]
#     [[],[],[],[].......]
# ]

# BGR [0,0,0]

In [14]:
print(img[0][400]) # prints first rows and 400th column

[62 22 34]


In [17]:
for i in range(100):
    for j in range(img.shape[1]):
        # (rows,columns,channels)
        img[i][j]=[random.randint(0,255),random.randint(0,255),random.randint(0,255)]

In [18]:
cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## copy and paste a part of image

In [20]:
tag=img[500:700,600:900]

In [21]:
img[100:300,100:400]=tag

In [22]:
cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()